### ISSUE TITLE
Outdated configs

### ISSUE THREAD

**Issue by chriske** [eliu/openshift-vagrant#1]
Hey!

First of all - thanks for your work!

Currently the config is outdated, because Ansible 2.7 is came out, and it is not able to install OpenShift Origin at this moment. (need to force the Ansible version before 2.7)

The second thing is, after I used Ansible 2.6.5, your node labels are not correct in the ansible hosts file.
Here are the new labels, and the exact same problem: https://github.com/openshift/openshift-ansible/issues/8327

And in the ansible hosts file the subdomain name was incorrect also.

Will you fix those issues? Or do you maintain this repository? Because I'm almost already done with the fixes, and if you want them, I can create a pull request.

Thanks!

**Comment by eliu** [comment]
Hi there, thanks for the feedbacks. This repo was created for personal use at first in order to study openshift before. Pull requests are always welcome although i havent maintain it for a while. i also hope this repo can help people to verify advanced openshift install on their local machine, always.

**Comment by eliu** [comment]
I have one question that since what version of openshift-ansible, this `'region': 'infra'` stuff started to be deprecated? Right now, this repo still make supports to install some older versions like `v3.6` and I believe we still need that deprecated label to work it out.

**Comment by chriske** [comment]
It's a good question. I didn't checked it exactly. I used your default config, and it didn't worked with your default version (3.9). After I made the node relabelling with the cli tool, the nodes became alive and my pods started to run.

**Comment by eliu** [comment]
Hi @chriske this issue has finally been fixed after a bunch of local deploying tests over and over again in these 8 days! Besides, this repo now supports OKD 3.10 deployment and set this version as default one right now. Kindly check them out and give it a try.

Feel free to re-open this issue if you've got any other questions.
