### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by gbraad** [eliu/openshift-vagrant#2]
Your use of the OpenShift logo is not in line with Red Hat's logo usage and guidelines.
Please do not distort or refrain from using it.

**Comment by eliu** [comment]
Hi @gbraad thanks for reminding me of this. i already read about the `guidelines`. I decide to remove this `disrorted` logo from repo soon. Anyways, this repo is only my personal project, not yet for some kind of commercial use.

**Comment by eliu** [comment]
Reference: [https://www.openshift.com/about/logos](url)

**Comment by gbraad** [comment]
personal or commercial is not the issue, it is published :-s... I just want to be sure as soon as you add a logo, it looks more official. We (Minishift) even have issues with our own logo, as it has been denied by our own legal team ;-P.
