### ISSUE TITLE
"vagrant up" fails on Manjaro Linux

### ISSUE THREAD

**Issue by joaompinto** [eliu/openshift-vagrant#5]
During the deployment script vagrant reports an error and fails, I have attached the log.
[fail.log](https://github.com/eliu/openshift-vagrant/files/2723923/fail.log)

**Comment by joaompinto** [comment]
I have commented this fix and the installation proceeded as expected, I guess that when the RELEASE does not match the shell is exiting with a non zero code.

    # Fix missing packages for openshift origin 3.11.0
    # https://lists.openshift.redhat.com/openshift-archives/dev/2018-November/msg00005.html
    #[ "$(version #{OPENSHIFT_RELEASE})" -eq "$(version 3.11)" ] && yum install -y centos-release-openshift-origin311

**Comment by eliu** [comment]
Thanks for the feedback. This non-zero error always happen when you choose okd versions other than `3.11`. A fix will be released for this.

**Comment by eliu** [comment]
A patch has been pushed to master branch. Feel free to reopen this issue if any further concerns you have.
