### ISSUE TITLE
openshift_node_labels no longer supported in OKD v3.11

### ISSUE THREAD

**Issue by brx75** [eliu/openshift-vagrant#7]
As stated in https://docs.okd.io/3.11/install/configuring_inventory_file.html#configuring-node-host-labels.

> You can no longer set the openshift_node_labels variable to change labels. See Node Group Definitions to modify the default node groups.

I think you have to remove 

```openshift_node_labels="{'node-role.kubernetes.io/compute': 'true'}"```

from ansible-hosts template file

**Comment by eliu** [comment]
It's there due to backward compatibility reason. These old openshift release needs this property in order to work property. Currently there's no harm for okd 3.11 from my side. Let me know if you have proved it conflicts the functionality of your clusters.

**Comment by brx75** [comment]
It fails during the run of
/home/vagrant/openshift-ansible/playbooks/prerequisites.yml playbook

**Comment by eliu** [comment]
@brx75 thanks for the feedback. now i can reproduce it. Will get back to you if any progress on this.

**Comment by eliu** [comment]
@brx75 this issue has been fixed. please give it a try to check if everything is ok. my laptop's available memory is not enough to bring up 3 vm nodes for OKD 3.11.

**Comment by brx75** [comment]
I'll check. About memory I found that 2GB seems too low for master node

**Comment by eliu** [comment]
Right, therefore all nodes' default memory has been increased within this fix.

**Comment by eliu** [comment]
Currently 3GB for master, and 2GB for nodes.

**Comment by eliu** [comment]
This issue is going to be stale since no further response for a while. Free free to re-open it if you want.
