### ISSUE TITLE
/home/vagrant/openshift-ansible/playbooks/byo/config.yml could not be found

### ISSUE THREAD

**Issue by michaelcourcy** [eliu/openshift-vagrant#8]
Hello

Following your doc I get this 
vagrant ssh master -c 'ansible-playbook /home/vagrant/openshift-ansible/playbooks/byo/config.yml'
ERROR! the playbook: /home/vagrant/openshift-ansible/playbooks/byo/config.yml could not be found

Instead I add to run this: 
vagrant ssh master -c 'ansible-playbook /home/vagrant/openshift-ansible/playbooks/deploy_cluster.yml'

**Comment by eliu** [comment]
Can you please provide the openshift release version that you choose to deploy?

**Comment by michaelcourcy** [comment]
I think it's 3.11 because I just clone your repo yesterday and follow you readme without changing anything.

**Comment by eliu** [comment]
It will go to new deploy script portion if you specify 3.11 ( the default version ), which means it never use `/home/vagrant/openshift-ansible/playbooks/byo/config.yml` for deployment.

It is recommended that you use the wrap-up script `oc-up.sh`  to boot up openshift-vagrant cluster.

Have you follow the instructions at README.md? 
https://github.com/eliu/openshift-vagrant#install-origin-cluster-using-ansible

**Comment by michaelcourcy** [comment]
Hello 

You're right I did not see this sentence

> Run the following command if you would like to install **origin previous to release-3.8**

My fault sorry.
